### PR TITLE
adding baseline css and blank htaccess

### PR DESCRIPTION
**Pull request by wesort**
Please review.

I am flexible on the iOS specific styles.

### CODE REVIEW

**Comment by NataliaLKB** [comment]
Points and questions to consider:
- Why push up a `.htaccess` file that is empty? [YAGNI](https://en.wikipedia.org/wiki/You_aren't_gonna_need_it)
- Also, why all the css, when we can't even know what we are styling yet? What is its purpose, and do we really need it?
- Best practices dictate that you should always Indent your html and css. 
    Resources:
    - http://www.smashingmagazine.com/2013/02/19/using-white-space-for-readability-in-html-and-css/
    - http://www.quepublishing.com/articles/article.aspx?p=24011&seqNum=3
    - http://google.github.io/styleguide/htmlcssguide.xml#Indentation
    - http://www.granneman.com/webdev/coding/formatting-and-indenting-your-html/
We can chat more about this tonight if you like.

**Comment by wesort** [comment]
- `.htaccess` : I agree. I suppose I was thinking this is standard by the end of a project like this (a webpage). But we don't need it yet so I will remove it.
- `CSS` : The reset that gives a good baseline to standardise across browsers. However, it doesn't need the word grid in the filename (legacy from the stylesheet I copied it from). I don't know that we need the iOS rotation specific polyfill stuff though so will remove those.
- Thanks for the resources, I will remove after this session. `reset.css` is written as such to be static and compact. However, I agree that writing to standards is better though. 

Should we lose the `reset.css` (without the iOS rotation stuff), reformat it to standards, or have a second stylesheet for everything AFTER the reset?

**Comment by NataliaLKB** [comment]
I would take out the IOS rotation stuff, as I am not sure yet if we will need it for this project.

I am open to either having multiple css files, or just one. What is your preference?

**Comment by wesort** [comment]
I would like to have the reset as I feel it forms a solid / known foundation for the project.

A secondary stylesheet would keep us from having to scroll through that messy reset. These can be merged later.

**Comment by NataliaLKB** [comment]
I agree. Lets have reset.css and another one for readability :+1:

**Pull request merged**
